#!/usr/bin/env python3
"""A `.c` may not declare `extern` for something another `.c` defines.

WHY.  The defect and the reason: RA2's port retyped four
`qboolean[7]` arrays to `bool[7]`, and another translation unit still declared
them `extern int []`.  Both files compiled.  Both linked.  Every map load wrote
21 bytes past the end of each array, and nothing -- not the compiler, not the
linker, not a review -- could see it, because the two declarations never meet.
`extern int botglobals;` in the tourney port is a fourth instance of the same
shape.

A declaration in a HEADER cannot drift like that: the file that defines the
object includes the same header, so the compiler checks the two against each
other and says so on the spot.  That is the whole rule -- not "extern is bad".

WHAT IS A FINDING.  An `extern` at file scope in a `.c`, naming a symbol that
this same file does not also define.  A forward `extern` for an object defined
LOWER DOWN IN THE SAME FILE is not a finding: the compiler sees both and checks
them, which is exactly the property the rule is after.  The monster files are
full of those -- `extern const mmove_t gekk_move_run;` ahead of the table that
uses it -- and rewriting them would trade a checked declaration for a tentative
definition, which is worse.

WHAT IS EXEMPT.  `src/g_ptrs.c` is generated by `genptr.py` from the definitions
themselves, so its ~400 externs cannot drift from what they name -- and
`check-ptrs` regenerates it in the build and fails on any difference.  A hand
edit there is caught by that check rather than this one.

USAGE
    tools/externs.py [--tree src]
    tools/externs.py --selftest
"""
import argparse
import os
import re
import shutil
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

EXEMPT_FILES = {
    'g_ptrs.c': 'generated by genptr.py from the definitions themselves; '
                'check-ptrs regenerates and diffs it in the build',
}

EXTERN = re.compile(r'^[ \t]*extern[ \t]+([^;{]*);', re.M)


def strip_comments(t):
    def blank(m):
        n = m.group(0).count('\n')
        return '\n' * n + ' ' * (len(m.group(0)) - n)
    t = re.sub(r'/\*.*?\*/', blank, t, flags=re.S)
    t = re.sub(r'//[^\n]*', lambda m: ' ' * len(m.group(0)), t)
    t = re.sub(r'"(?:\\.|[^"\\\n])*"', lambda m: ' ' * len(m.group(0)), t)
    return t


def declarator_names(body):
    """The identifiers an `extern <body>;` declares.

    A function declaration names one thing and its parameters name others, so
    the parameter list is cut away first -- without that, `extern void
    Move_Calc(edict_t *ent, vec3_t dest, ...)` reports `ent` and `dest` as two
    undefined externs, which is what the first draft of this tool did.
    """
    body = body.strip()
    fn = re.match(r'^(.*?)\b(\w+)\s*\(', body)
    if fn and '(' in body:
        return [fn.group(2)]
    out = []
    for part in body.split(','):
        m = re.search(r'(\w+)\s*(?:\[[^\]]*\])?\s*$', part.strip())
        if m:
            out.append(m.group(1))
    return out


def toplevel_defs(code):
    """Every symbol this file defines at file scope.

    Brace depth is tracked so a CALL inside a function body does not count as a
    definition -- the loose version of this check treated `ED_CallSpawn(ent);`
    in the middle of a function as g_newdm.c defining it, and reported nothing.
    """
    defs = set()
    depth = 0
    for line in code.split('\n'):
        if depth == 0:
            s = line.rstrip()
            if s and not s[0].isspace() and not s.lstrip().startswith(('extern', '#')):
                # a definition or a prototype at column 0
                m = re.match(r'^[A-Za-z_][\w \t\*]*?\b(\w+)\s*\(', s)
                if m:
                    defs.add(m.group(1))
                else:
                    m = re.match(r'^[A-Za-z_][\w \t\*]*?\b(\w+)\s*(?:\[[^\]]*\])?\s*(=|;|$)', s)
                    if m:
                        defs.add(m.group(1))
        depth += line.count('{') - line.count('}')
        if depth < 0:
            depth = 0
    return defs


def sources(tree):
    out = []
    for root, dirs, files in os.walk(tree):
        dirs[:] = [d for d in dirs if not d.startswith(('debug', 'release', '__'))]
        for f in sorted(files):
            if f.endswith('.c'):
                out.append(os.path.join(root, f))
    return out


def scan(tree):
    hits = []
    for path in sources(tree):
        if os.path.basename(path) in EXEMPT_FILES:
            continue
        code = strip_comments(open(path, encoding='utf-8').read())
        defs = toplevel_defs(code)
        for m in EXTERN.finditer(code):
            line = code.count('\n', 0, m.start()) + 1
            for name in declarator_names(m.group(1)):
                if name not in defs:
                    hits.append((os.path.relpath(path, REPO), line, name))
    return hits



# ---------------------------------------------------------------- signatures
#
# The second half of the same rule.  `extern` is a spelling, not a mechanism:
# `void drawbbox(edict_t *self);` at column 0 in a .c declares another file's
# symbol exactly as `extern void drawbbox(...)` does, and this tree has 250-odd
# of them -- most of them baseq2's own spawn table.  Moving every one into a
# header is the ideal; what a header BUYS is the cross-check, so the check is
# done here instead: a cross-file declaration whose types disagree with the
# definition is a finding, wherever it is written.
#
# It has already earned its place.  Moving `Move_Calc` into g_local.h made gcc
# reject `src/rogue/g_newfnc.c`'s own copy, which said `vec3_t dest` where
# g_func.c says `const vec3_t dest` -- Ground Zero's prototype had been one
# qualifier out since the mission-pack merge, invisible because the two
# declarations never met.

KEYWORDS = {'void', 'int', 'char', 'float', 'short', 'long', 'unsigned',
            'signed', 'bool', 'double', 'byte', 'const', 'struct', 'union',
            'enum'}

DEFN = re.compile(r'^([A-Za-z_][\w \t\*]*?)\b(\w+)\s*(\([^;]*\))\s*$', re.M)
PROTO = re.compile(r'^(?:extern\s+)?([A-Za-z_][\w \t\*]*?)\b(\w+)\s*(\([^;]*\))\s*;\s*$')


def _param_type(text):
    """A parameter's TYPE, with its name removed.

    `edict_t *self` and `edict_t *ent` are the same parameter; `vec3_t dest`
    and `const vec3_t dest` are not.  A function-pointer parameter is compared
    whole, because its own parameter names are equally irrelevant and equally
    hard to strip.
    """
    t = text.strip()
    if '(' in t:
        return re.sub(r'\s+', '', t)
    arr = ''
    m = re.search(r'((?:\[[^\]]*\])+)$', t)
    if m:
        arr, t = m.group(1), t[:m.start()]
    t = t.strip()
    m = re.match(r'^(.*?)\b(\w+)$', t)
    if m and m.group(2) not in KEYWORDS and m.group(1).strip():
        t = m.group(1)
    return re.sub(r'\s+', '', t) + re.sub(r'\s+', '', arr)


def _signature(ret, params):
    inner = params[params.index('(') + 1:params.rindex(')')]
    if not inner.strip() or inner.strip() == 'void':
        parts = ['void']
    else:
        parts, depth, cur = [], 0, ''
        for ch in inner:
            if ch == '(':
                depth += 1
            elif ch == ')':
                depth -= 1
            if ch == ',' and depth == 0:
                parts.append(cur)
                cur = ''
            else:
                cur += ch
        parts.append(cur)
        parts = [_param_type(x) for x in parts]
    return (re.sub(r'\s+', '', ret), tuple(parts))


def definitions(tree):
    """name -> (file, signature) for every function defined at file scope."""
    out = {}
    for path in sources(tree):
        code = strip_comments(open(path, encoding='utf-8').read())
        depth = 0
        for line in code.split('\n'):
            if depth == 0:
                m = DEFN.match(line.rstrip())
                if m and not line.lstrip().startswith(('extern', 'typedef', '#')):
                    out.setdefault(m.group(2), (path, _signature(m.group(1), m.group(3))))
            depth += line.count('{') - line.count('}')
            depth = max(depth, 0)
    return out


def scan_signatures(tree):
    defs = definitions(tree)
    hits = []
    for path in sources(tree):
        if os.path.basename(path) in EXEMPT_FILES:
            continue
        code = strip_comments(open(path, encoding='utf-8').read())
        depth = 0
        for i, line in enumerate(code.split('\n'), 1):
            if depth == 0:
                s = line.rstrip()
                if not s.lstrip().startswith(('static', 'typedef', '#')):
                    m = PROTO.match(s)
                    if m and m.group(2) in defs:
                        where, want = defs[m.group(2)]
                        if where != path:
                            got = _signature(m.group(1), m.group(3))
                            if got != want:
                                hits.append((os.path.relpath(path, REPO), i,
                                             m.group(2), got, want,
                                             os.path.relpath(where, REPO)))
            depth += line.count('{') - line.count('}')
            depth = max(depth, 0)
    return hits


SELFTEST_CLEAN = {
    # a forward extern for something this file defines lower down: checked by
    # the compiler, so not a finding
    'fwd.c': 'extern const int table;\nvoid use(void) { (void)table; }\nconst int table = 1;\n',
    # a function declaration whose PARAMETERS must not be reported
    'params.c': 'extern void Param_Named(int *ent, int dest);\n'
                'void Param_Named(int *ent, int dest) { (void)ent; (void)dest; }\n',
}

SELFTEST_MUTANTS = [
    ('an object another .c defines', 'bad.c', 'extern int stalker_mins;\n'),
    ('a function another .c defines', 'bad.c', 'extern void drawbbox(int *self);\n'),
    ('a call is not a definition', 'bad.c',
     'extern void ED_CallSpawn(int *e);\nvoid f(int *e) { ED_CallSpawn(e); }\n'),
    ('one of several comma declarators', 'bad.c',
     'extern int here, elsewhere;\nint here = 1;\n'),
]


def selftest():
    ok = True
    tmp = tempfile.mkdtemp(prefix='externs-selftest-')
    try:
        for name, body in SELFTEST_CLEAN.items():
            open(os.path.join(tmp, name), 'w').write(body)
        base = scan(tmp)
        if base:
            print('!! selftest: the clean tree reported %s' % (base,))
            ok = False
        else:
            print('   [control] forward extern + parameter names: 0 findings')
        for why, fname, body in SELFTEST_MUTANTS:
            p = os.path.join(tmp, fname)
            open(p, 'w').write(body)
            got = scan(tmp)
            os.remove(p)
            if not got:
                print('!! selftest: %s was NOT caught' % why)
                ok = False
            else:
                print('   [control] %s -> caught (%s)' % (why, got[0][2]))

        # ...and the signature half, which `extern` alone cannot see.
        open(os.path.join(tmp, 'owner.c'), 'w').write(
            'void Move_Calc(int *ent, const int *dest)\n{\n    (void)ent; (void)dest;\n}\n')
        open(os.path.join(tmp, 'user.c'), 'w').write(
            'void Move_Calc(int *ent, const int *dest);\nvoid g(void) { }\n')
        if scan_signatures(tmp):
            print('!! selftest: a MATCHING cross-file prototype was reported')
            ok = False
        else:
            print('   [control] matching cross-file prototype: 0 findings')
        open(os.path.join(tmp, 'user.c'), 'w').write(
            'void Move_Calc(int *ent, int *dest);\nvoid g(void) { }\n')
        got = scan_signatures(tmp)
        if not got:
            print('!! selftest: a const-dropped prototype was NOT caught')
            ok = False
        else:
            print('   [control] a dropped const on a parameter -> caught')
        os.remove(os.path.join(tmp, 'user.c'))
        os.remove(os.path.join(tmp, 'owner.c'))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--tree', default=os.path.join(REPO, 'src'))
    ap.add_argument('--selftest', action='store_true')
    a = ap.parse_args()
    if a.selftest:
        return 0 if selftest() else 1
    tree = os.path.abspath(a.tree)
    hits = scan(tree)
    for path, line, name in hits:
        print('!! %s:%d: extern %s -- declare it in a header the defining file '
              'includes' % (path, line, name))
    sigs = scan_signatures(tree)
    for path, line, name, got, want, where in sigs:
        print('!! %s:%d: %s disagrees with its definition in %s\n'
              '     declared %s\n     defined  %s' %
              (path, line, name, where, got, want))
    print('externs: %d cross-file extern(s) in a .c, %d signature disagreement(s)'
          % (len(hits), len(sigs)))
    return 1 if (hits or sigs) else 0


if __name__ == '__main__':
    sys.exit(main())
